import Link from "next/link";
import { ArrowRight, Building2, Check, ExternalLink, FileText, HelpCircle, ShieldCheck } from "lucide-react";
import { Breadcrumbs } from "@/components/Common";
import { blogPosts, corporateDetail } from "@/data/site";
import { publishedCaseExamples as caseExamples } from "@/data/case-examples";
import { siteUrl } from "@/lib/site";

const relatedPost=blogPosts.find(post=>post.category==="기업·법인 행정");
const relatedExample=caseExamples.find(item=>item.category==="business");
const canonical=siteUrl("/services/corporate");

export function CorporateDetail(){
  const structuredData={"@context":"https://schema.org","@graph":[{"@type":"Service",name:"기업·법인 행정업무",serviceType:"기업·단체 행정기관 제출업무 지원",provider:{"@type":"ProfessionalService",name:"가든 행정사사무소"},url:canonical},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"홈",item:canonical.replace("/services/corporate","")},{"@type":"ListItem",position:2,name:"업무 분야",item:canonical.replace("/corporate","")},{"@type":"ListItem",position:3,name:"기업·법인 행정",item:canonical}]},{"@type":"FAQPage",mainEntity:corporateDetail.faqs.map(([question,answer])=>({"@type":"Question",name:question,acceptedAnswer:{"@type":"Answer",text:answer}}))}]};
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData).replace(/</g,"\\u003c")}}/>
    <section className="corporate-hero"><div className="shell corporate-hero-grid"><div><p className="eyebrow">CORPORATE ADMINISTRATION</p><h1>기업 운영에 필요한 행정업무,<br/><strong>사업에 집중할 수 있도록 체계적으로 지원합니다.</strong></h1><p>법인·단체의 인허가와 변경신고, 행정기관 제출서류와 사업계획서 등 기업 운영 과정에서 발생하는 행정절차를 안내합니다.</p><div className="button-row"><Link className="button gold" href="/contact?service=corporate">기업 행정업무 상담하기 <ArrowRight/></Link><a className="button outline-light" href="#corporate-support">지원 업무 확인하기</a></div></div><div className="corporate-flow" aria-label="기업 행정업무 흐름"><div><Building2/><b>기업·단체</b></div><span>→</span><div><FileText/><b>행정서류</b></div><span>→</span><div><Check/><b>기관 제출</b></div><ul>{["행정절차 확인","제출서류 작성","변경신고 지원","진행 단계별 안내"].map(item=><li key={item}>{item}</li>)}</ul></div></div></section>
    <Breadcrumbs items={[{label:"업무 분야",href:"/services"},{label:"기업·법인 행정"}]}/>

    <section className="section corporate-quick"><div className="shell"><div className="corporate-heading"><p className="eyebrow">QUICK CHECK</p><h2>어떤 기업 행정업무가 필요하신가요?</h2><p>현재 기업이나 단체의 상황과 가까운 항목을 선택해 주세요. 행정업무와 등기·세무 등 별도 전문영역을 함께 구분합니다.</p></div><div className="immigration-question-grid">{corporateDetail.quickQuestions.map((question,index)=><Link className="immigration-question-card" key={question} href="/contact?service=corporate"><span className="immigration-question-number">{String(index+1).padStart(2,"0")}</span><strong className="immigration-question-title">{question}</strong><p className="immigration-question-description">{corporateDetail.quickDescriptions[index]}</p><span className="immigration-question-action">상담 항목 선택 <ArrowRight/></span></Link>)}</div></div></section>

    <section className="section soft"><div className="shell"><div className="corporate-heading"><p className="eyebrow">ORGANIZATION TYPES</p><h2>기업과 단체의 형태에 따라<br/>필요한 행정절차가 달라집니다.</h2><p>같은 변경사항도 조직 형태와 주무관청에 따라 허가·신고·보고 방식이 달라질 수 있습니다.</p></div><div className="corporate-type-grid">{corporateDetail.organizationTypes.map((type,index)=><article key={type.title}><span>0{index+1}</span><h3>{type.title}</h3><ul>{type.items.map(item=><li key={item}><Check/>{item}</li>)}</ul></article>)}</div></div></section>

    <section className="section" id="corporate-support"><div className="shell"><div className="corporate-heading"><p className="eyebrow">SERVICE SCOPE</p><h2>기업·법인 행정 주요 지원 업무</h2><p>제출기관과 문서 성격, 다른 법률의 자격 제한을 확인한 뒤 행정사가 수행할 수 있는 범위를 정합니다.</p></div><div className="corporate-support-list">{corporateDetail.supports.map((item,index)=><article key={item.title}><span>{String(index+1).padStart(2,"0")}</span><div><h3>{item.title}</h3><p>{item.intro}</p></div><ul>{item.items.map(value=><li key={value}>{value}</li>)}</ul><small>{item.note}</small>{item.title==="기업 인허가 관리"&&<Link href="/services/permits">인허가 상세 안내 <ArrowRight/></Link>}</article>)}</div></div></section>

    <section className="corporate-nonprofit"><div className="shell corporate-nonprofit-layout"><div><p className="eyebrow">NONPROFIT CORPORATION</p><h2>비영리법인은 등기보다<br/><strong>주무관청과 설립허가 확인이 먼저입니다.</strong></h2><p>비영리법인은 목적사업을 담당하는 주무관청을 확인하고, 설립 목적과 사업 수행 능력, 재정적 기반과 제출서류를 준비하여 설립허가를 신청하는 절차가 필요합니다.</p><small>설립허가 후 법인등기와 세무신고는 각각 관련 전문가 또는 공식 절차를 확인해야 합니다.</small></div><div><ul>{corporateDetail.nonprofitChecks.map(item=><li key={item}><Check/>{item}</li>)}</ul><ol>{corporateDetail.nonprofitProcess.map((item,index)=><li key={item}><span>{String(index+1).padStart(2,"0")}</span>{item}</li>)}</ol></div></div></section>

    <section className="section"><div className="shell corporate-consult"><div><p className="eyebrow">WHEN TO CHECK</p><h2>다음 상황이라면 기업 행정업무를 확인해 보세요.</h2><p>기업 업무는 하나의 절차로 끝나지 않을 수 있습니다. 행정기관 제출업무와 등기·세무·노무 등 다른 전문영역을 먼저 구분해야 불필요한 시간과 비용을 줄일 수 있습니다.</p></div><ul>{corporateDetail.consultationChecks.map(item=><li key={item}><Check/>{item}</li>)}</ul></div></section>

    <section className="section corporate-expert-section"><div className="shell"><div className="corporate-heading"><p className="eyebrow">SCOPE GUIDE</p><h2>어떤 전문가의 업무인지부터 구분합니다.</h2><p>아래는 일반적인 안내이며 구체적인 업무 범위는 개별 사안과 관계 법령에 따라 확인합니다.</p></div><div className="corporate-expert-grid"><article><span>ADMINISTRATIVE SCRIVENER</span><h3>행정사 영역 예시</h3><ul>{corporateDetail.adminScope.map(item=><li key={item}><Check/>{item}</li>)}</ul></article><article><span>OTHER SPECIALISTS</span><h3>별도 전문영역 예시</h3><dl>{corporateDetail.specialistScope.map(([area,expert])=><div key={area}><dt>{area}</dt><dd>{expert}</dd></div>)}</dl></article></div></div></section>

    <section className="section"><div className="shell corporate-prep"><div><p className="eyebrow">PREPARE</p><h2>상담 전, 다음 내용을 알려주세요.</h2><p>자료가 모두 준비되지 않았더라도 현재 조직의 목적과 진행 단계, 필요한 행정절차를 알려주시면 추가 확인사항을 안내해 드립니다.</p></div><ul>{corporateDetail.preparations.map((item,index)=><li key={item}><span>{String(index+1).padStart(2,"0")}</span>{item}</li>)}</ul></div></section>

    <section className="section soft"><div className="shell"><div className="corporate-heading center"><p className="eyebrow">PROCESS</p><h2>기업·법인 행정업무 진행 절차</h2><p>업무 영역과 관할기관을 먼저 구분한 뒤 필요한 자료와 역할 범위를 안내합니다.</p></div><ol className="permit-process corporate-process">{corporateDetail.process.map(([title,body],index)=><li key={title}><span>{String(index+1).padStart(2,"0")}</span><h3>{title}</h3><p>{body}</p></li>)}</ol></div></section>

    <section className="corporate-recurring"><div className="shell corporate-recurring-layout"><div><p className="eyebrow">ONGOING ADMINISTRATION</p><h2>기업 행정업무는<br/>설립 이후에도 계속됩니다.</h2><p>정기관리 상품을 판매하는 것은 아니며, 실제 변경·갱신·보고 업무가 발생할 때 필요한 절차를 개별 상담합니다.</p><Link className="button gold" href="/contact?service=corporate">기업 행정업무 상담하기</Link></div><div>{corporateDetail.recurring.map((item,index)=><span key={item}><b>{String(index+1).padStart(2,"0")}</b>{item}</span>)}</div></div></section>

    <section className="section"><div className="shell corporate-caution"><ShieldCheck/><div><p className="eyebrow">PLEASE NOTE</p><h2>기업·법인 행정업무 의뢰 전 확인해 주세요.</h2><ul>{corporateDetail.cautions.map(item=><li key={item}>{item}</li>)}</ul></div></div></section>

    <section className="section soft"><div className="shell corporate-official"><div><p className="eyebrow">OFFICIAL INFORMATION</p><h2>조직 형태와 주무관청별 최신 기준을 확인합니다.</h2><p>비영리법인 허가서류와 변경 절차는 주무관청별 규칙과 안내가 다를 수 있습니다.</p><small>공식 정보 최종 확인일: {corporateDetail.lastReviewed}</small></div><div>{corporateDetail.officialSources.map(source=><a href={source.url} target="_blank" rel="noreferrer" key={source.url}>{source.label}<ExternalLink/></a>)}</div></div></section>

    <section className="section"><div className="shell corporate-faq"><div><p className="eyebrow">FAQ</p><h2>자주 묻는 질문</h2><p>기업 형태와 주무관청에 따라 달라지는 부분을 구분해 안내합니다.</p></div><div className="faq-list">{corporateDetail.faqs.map(([question,answer])=><details key={question}><summary>{question}<span>＋</span></summary><p>{answer}</p></details>)}</div></div></section>

    {(relatedExample||relatedPost)&&<section className="section corporate-related"><div className="shell"><div className="corporate-heading"><p className="eyebrow">RELATED CONTENT</p><h2>관련 업무사례와 안내 글</h2></div><div className="corporate-related-grid">{relatedExample&&<article><small>업무사례</small><h3>{relatedExample.title}</h3><p>{relatedExample.summary}</p><Link href={`/cases/${relatedExample.slug}`}>사례 상세 보기 <ArrowRight/></Link></article>}{relatedPost&&<article><small>발행된 블로그</small><h3>{relatedPost.title}</h3><p>{relatedPost.summary}</p><Link href={`/blog/${relatedPost.slug}`}>안내 글 보기 <ArrowRight/></Link></article>}</div></div></section>}

    <section className="corporate-final"><div className="shell"><HelpCircle/><div><p className="eyebrow">CORPORATE CONSULTATION</p><h2>복잡한 기업 행정업무,<br/><strong>필요한 절차와 담당 영역부터 구분해 드립니다.</strong></h2><p>기업·단체의 형태와 현재 진행 단계, 필요한 업무를 알려주시면 상담 가능한 행정업무와 준비사항을 안내해 드립니다.</p></div><div className="button-row"><Link className="button gold" href="/contact?service=corporate">기업 행정업무 상담하기</Link><Link className="button outline-light" href="/services">전체 업무 분야 보기</Link></div></div></section>
  </>;
}
